name = "Ong Zhen Yang"
rol = [
    "Digital Supply Chain Specialist"
]
email = "zyresume@outlook.com"
phone = "(+65) 8013 7483"
birthday = "October 25, 1997"
location = "Singapore"
avatar = "./config/assets/avatars/zhenyang.png"
username = "GoodbyeKittyy" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d63818.10390949217!2d103.84932459490926!3d1.397543588831973!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1515bfb2d263%3A0xc71c56458ac08497!2sSIT%20Punggol%20Campus%20-%20East%20Zone%20(U%2FC)!5e0!3m2!1sen!2ssg!4v1723616610627!5m2!1sen!2ssg"

presentation = """
I am a Digital Supply Chain Specialist from Singapore with 5 years of academic and practical experience. Through 7+ years of continuous academic learning and upskilling, I am proficient in over 30 programming languages and well-versed in Digital Transformation skills including AI Engineering, Quantum Computing, FullStack Development and Software Engineering. I am a dedicated Team Leader, well equipped as a Six Sigma Black Belt to transform complex problems into productive solutions based on the user's pain points.
"""

