[[doing]]
title = "Statistical Modeling"
icon = "./config/assets/icons/DataAnalysis.png"


[[doing]]
title = "Automation & Scripting"
icon = "./config/assets/icons/AutomationScripting.png"

[[doing]]
title = "Web Development"
icon = "./config/assets/icons/WebDevelopment.png"

[[doing]]
title = "Process Optimization"
icon = "./config/assets/icons/ProcessOptimization.png"

[[doing]]
title = "Software & API"
icon = "./config/assets/icons/SoftwareAPI.png"
