[[doing]]
title = "Supply Chain Digitalization"
icon = "./config/assets/icons/DataAnalysis.png"

[[doing]]
title = "Lean Six Sigma"
icon = "./config/assets/icons/SoftwareAPI.png"

[[doing]]
title = "Fullstack Development"
icon = "./config/assets/icons/AutomationScripting.png"

[[doing]]
title = "Software Development"
icon = "./config/assets/icons/AIEngineering.png"

[[doing]]
title = "AI & ML Engineering"
icon = "./config/assets/icons/WebDevelopment.png"

[[doing]]
title = "Enterprise Integration & API"
icon = "./config/assets/icons/ProcessOptimization.png"




