############### Section config ##################
#################################################
title = "Soft Skills"
enabled = true # false

################ Skills #########################
#################################################
[[skills]]
title = "Critical Problem Solver"
icon = "./config/assets/icons/gear.svg"
text = "Analyzes the Why, How and What of user and business challenges to architect purposeful technology solutions that deliver measurable impact."

[[skills]]
title = "Agile Project Execution"
icon = "./config/assets/icons/bolt.svg"
text = "Delivers consistent and timely results across Agile sprints and SCRUM reviews through strategic task prioritization."

[[skills]]
title = "Continuous Learner"
icon = "./config/assets/icons/comment.svg"
text = "Embraces challenges beyond comfort zones and can rapidly master new technologies and methodologies to stay ahead of evolving project requirements."

[[skills]]
title = "Collaborative Team Player"
icon = "./config/assets/icons/user.svg"
text = "Excels in effective communication, knowledge sharing, and collective problem-solving to elevate team productivity and innovation."
