############### Section config ##################
#################################################
title = "Soft Skills"
enabled = true # false

################ Skills #########################
#################################################

[[skills]]
title = "Problem Solver"
icon = "./config/assets/icons/gear.svg"
text = "Excels in problem-solving by meticulously analyzing challenges, breaking them down into manageable components."

[[skills]]
title = "Timely"
icon = "./config/assets/icons/user.svg"
text = "Demonstrates timeliness in all aspects of work while efficiently prioritizing tasks."

[[skills]]
title = "Adaptable & Fast Learner"
icon = "./config/assets/icons/comment.svg"
text = "Quickly adjusts to any new project requirements. Constantly goes out of comfort zone to be a lifelong learner, embracing new technologies and methodologies."

[[skills]]
title = "Teamwork & Effective Communication"
icon = "./config/assets/icons/user.svg"
text = "Contributes to a positive work environment where ideas flourish, productivity improves, and teamwork thrives."
