############### Section config ##################
#################################################
title = "Soft Skills"
enabled = true # false

################ Skills #########################
#################################################

[[skills]]
title = "Strategic Problem Solver"
icon = "./config/assets/icons/gear.svg"
text = "Analyzes the Why, How, and What of user and business pain points to architect purposeful technology solutions that drive meaningful impact."

[[skills]]
title = "Results-Driven & Agile"
icon = "./config/assets/icons/user.svg"
text = "Delivers consistent results across Agile & SCRUM workflows through strategic task prioritization and efficient execution."

[[skills]]
title = "Continuous Learner"
icon = "./config/assets/icons/comment.svg"
text = "Embraces challenges beyond comfort zones, rapidly mastering new technologies and methodologies to stay ahead of evolving project requirements."

[[skills]]
title = "Collaborative Worker"
icon = "./config/assets/icons/user.svg"
text = "Fosters positive team dynamics through effective communication, knowledge sharing, and collective problem-solving to elevate productivity and innovation."
